version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
    - 27017:27017

    volumes:
    - ./dbdata:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
